version: '3'
services:
  myapplication:
    image: backend:1.0
    environment: 
      - MONGODB_CONNSTRING=mongodb://youssef:youssef123@mongodb
    ports:
      - 3000:3000
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=youssef
      - MONGO_INITDB_ROOT_PASSWORD=youssef123